### PR TITLE
initial import

### PR DESCRIPTION
**Pull request by jyane**
~~This is the part 1 of imports.~~

edit:
All

### CODE REVIEW

**Comment by jyane** [comment]
Could I add the travis CI?

**Comment by ejona86** [comment]
I just enabled Travis-CI for this repo.

**Comment by ejona86** [comment]
We'll also need to enable the CLA webhook.

**Comment by jyane** [comment]
@ ejona86 Thanks!

File: pom.xml [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
+  <modelVersion>4.0.0</modelVersion>
+
+  <groupId>io.grpc</groupId>
+  <artifactId>grpc-java-api-checker</artifactId>
+  <version>1.0-SNAPSHOT</version>
+
+  <name>grpc-java-api-checker</name>
+  <description>An Error Prone plugin that checks for usages of grpc-java APIs.</description>
```
Comment (ericgribkoff) [inline pom.xml]: Myabe this should be slightly more specific about what APIs it checks for. Could this be changed to "An Error Prone plugin that checks for usages of grpc-java experimental or internal APIs."?

**Comment by ericgribkoff** [comment]
Commenting to see if the CLA bot is triggered...

**Comment by jyane** [comment]
Commenting as a pull request owner is needed?

**Comment by jyane** [comment]
🤔

**Comment by ericgribkoff** [comment]
The CLA bot will automatically activate on future PRs from now on - we added the bot to this repo after the PR was created, so some activity here was necessary to catch the bot's attention (and verify that it was working properly) :)

**Comment by ericgribkoff** [comment]
@jyane Could you add in the documentation for using this in a project? I believe this was present earlier in your repository, but it seems to be gone now. If documentation isn't ready yet, just a comment here on how to set this up would work as well. I'm probably missing something obvious, but attempting to apply this checker in the same manner as [Guava's Beta API checker](https://github.com/google/guava-beta-checker#gradle) doesn't seem to have any effect when I build the project. I installed and added this checker to our Hello World project, but the code can include `@ExperimentalApi` and `@Internal` references without any complaint upon building with gradle.

**Comment by jyane** [comment]
@ericgribkoff 
I just pushed the documents and examples.

I'm sorry.
I thought that creating 2 or 3 pull requests would be better because importing all source codes would be hard for code review.
I'm not good at English, I thought documentation review will cost.

I made obsolete the previous repository.
https://github.com/jyane/obsolate

> I'm probably missing something obvious, but attempting to apply this checker in the same manner as Guava's Beta API checker doesn't seem to have any effect when I build the project.

Using grpc-java examples is no effects because their examples are under the `io.grpc` package (`io.grpc.examples`).
Currently, this tool excluding `io.grpc` package and starting with `io.grpc.` package.
https://github.com/grpc/grpc-java-api-checker/pull/1/files#diff-67f7914507ae4e883be04d03c3bef39bR100

File: README.md [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+#### Maven
+The example is [here](examples/maven)
+
+``` sh
+cd examples/maven/
+mvn compile
+```
+
+#### Gradle
+The example is [here](examples/gradle)
```
Comment (ericgribkoff) [inline README.md]: This is optional: Is it possible to combine `examples/gradle/` and `example/maven/` into one directory (just `example/`) and just have both sets of build files in the same directory? It looks like the actual code for the example is duplicated.

File: README.md [hunk 3]
```diff
@@ -0,0 +1,66 @@
+# grpc-java-api-checker
+
+[![Build Status](https://travis-ci.org/grpc/grpc-java-api-checker.svg?branch=master)](https://travis-ci.org/grpc/grpc-java-api-checker)
+
+An Error Prone plugin that checks for usages of grpc-java APIs that are annotated with `@ExperimentalApi` or `@Internal` annotation.
```
Comment (ericgribkoff) [inline README.md]: How about dropping the last word of this sentence ("annotation"), and having just:

> An Error Prone plugin that checks for usages of grpc-java APIs that are annotated with `@ExperimentalApi` or `@Internal`.

File: README.md [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+
+**NOTE: Currently grpc-java-api-checker does not work. But you can use this with HEAD of grpc-java. This problem will be fixed by grpc-java `1.10.0`.**
```
Comment (ericgribkoff) [inline README.md]: Let's instead say something like:

> **NOTE: grpc-java-api-checker works with grpc-java version `1.10.0` or greater.**

(I'll be releasing grpc-java `1.10.0` next week)

File: README.md [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+```
+
+## Usage
+
+Using the grpc-java-api-checker requires configuring your project to build with the Error Prone Java compiler.
+You can see the Error Prone documents [here](http://errorprone.info/).
+
+### Examples
+
+If you want to see grpc-java-api-checker is working with examples, first you should do the local publish.
```
Comment (ericgribkoff) [inline README.md]: Let's also let people know that this is temporary, as once we publish to Maven they won't need to do the local install step. I'd change this sentence to something like:

> To use grpc-java-api-checker, you must first publish it locally. (TODO: update with link to jars on Maven once they are published)

File: examples/gradle/build.gradle [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+repositories {
+    mavenLocal()
+    mavenCentral()
+}
+
+dependencies {
+    // See: https://github.com/grpc/grpc-java/commit/0c210322216b9509855663a0ee4fc26c5b0e4ec7
+    // If you want to build the grpc-java 1.11.0-SNAPSHOT, see the official documents:
+    // https://github.com/grpc/grpc-java/blob/master/COMPILING.md
+    compile "io.grpc:grpc-core:1.11.0-SNAPSHOT"
```
Comment (ericgribkoff) [inline examples/gradle/build.gradle]: Ah, I see, it is unfortunate that `1.10.0` isn't already released :( Still, that will be out in just a week, so I think it's ok to just depend on `io.grpc:grpc-core:1.10.0` here, even though it doesn't quite exist yet. What do you think?

File: src/main/java/io/grpc/annotations/checkers/ExperimentalApiChecker.java [hunk 7]
```diff
@@ -0,0 +1,67 @@
...
+import com.sun.source.tree.Tree;
+import java.util.Map.Entry;
+import java.util.Optional;
+import javax.lang.model.element.AnnotationMirror;
+import javax.lang.model.element.AnnotationValue;
+import javax.lang.model.element.ExecutableElement;
+
+@AutoService(BugChecker.class)
+@BugPattern(
+    name = "ExperimentalApi",
```
Comment (ericgribkoff) [inline src/main/java/io/grpc/annotations/checkers/ExperimentalApiChecker.java]: Do we need to worry about name conflicts with these plugins? I'm curious what happens if library X also releases an annotation checker named "ExperimentalApi" - would there be any way for a user to include both gRPC's "ExperimentalApi" checker and library X's "ExperimentalApi" checker? If not and the names would conflict, should the name here be changed something like "GrpcExperimentalApi"?

I know Guava's Beta API checker is just named "BetaApi", so maybe there's no need for including gRPC in the name here, but just wanted to check. 

@ejona86 any thoughts?

**Review by ericgribkoff — COMMENTED** [review]
I haven't made it through the tests yet, but this looks very good! I have some minor feedback on the documentation/examples, sending those comments now.

@jyane Hah, it makes sense that `io.grpc` must be excluded :) Thanks for the explanation. If I had know what I was doing, it would have been fine to keep documentation as a follow-up PR - but I found it very helpful and only suggested a couple small changes, so I don't think there's any reason to delay it's inclusion now.

I did run into an issue with our generated code including an `@ExperimentalApi` annotation, which triggers an error/warning from the `@Internal` checker. I sent out https://github.com/grpc/grpc-java/pull/4039 as a possible fix, but please let me know if you have a better solution for this.

File: src/main/java/io/grpc/annotations/checkers/ExperimentalApiChecker.java (hunk 7 above)
Comment (ejona86) [reply src/main/java/io/grpc/annotations/checkers/ExperimentalApiChecker.java]: I expect this name is used for squelching warnings with `@SuppressWarnings` as well as configuring how it is enabled (off vs error vs warning). We should probably include "grpc".

**Comment by jyane** [comment]
> I did run into an issue with our generated code including an @ExperimentalApi annotation, which triggers an error/warning from the @Internal checker. I sent out grpc/grpc-java#4039 as a possible fix, but please let me know if you have a better solution for this.

I've commented here.
https://github.com/grpc/grpc-java/pull/4039#issuecomment-363310639

I'm sorry, there is 17 hours time differences between Tokyo and Bay Area.
I will address the comments, at tonight (JST).

File: examples/gradle/build.gradle (hunk 6 above)
Comment (jyane) [reply examples/gradle/build.gradle]: It's fine :)

File: README.md (hunk 2 above)
Comment (jyane) [reply README.md]: Yeah, they are duplicated.
I will merge them.

File: src/main/java/io/grpc/annotations/checkers/ExperimentalApiChecker.java (hunk 7 above)
Comment (jyane) [reply src/main/java/io/grpc/annotations/checkers/ExperimentalApiChecker.java]: I agree with ericgribkoff and ejona86. I think providing the explicit name would be helpful for users as well.

I will change checker names to `GrpcInternal` and `GrpcExperimentalApi`.

**Comment by jyane** [comment]
Thanks!
I think I have addressed all comments, PTAL.

File: examples/build.gradle [hunk 8]
```diff
@@ -21,10 +21,7 @@ repositories {
 }
 
 dependencies {
-    // See: https://github.com/grpc/grpc-java/commit/0c210322216b9509855663a0ee4fc26c5b0e4ec7
-    // If you want to build the grpc-java 1.11.0-SNAPSHOT, see the official documents:
-    // https://github.com/grpc/grpc-java/blob/master/COMPILING.md
-    compile "io.grpc:grpc-core:1.11.0-SNAPSHOT"
+    compile 'io.grpc:grpc-netty:1.10.0'
```
Comment (ericgribkoff) [inline examples/build.gradle]: grpc-core instead of grpc-netty?

File: src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java [hunk 9]
```diff
@@ -0,0 +1,105 @@
...
+import com.sun.source.tree.CompilationUnitTree;
+import com.sun.source.tree.IdentifierTree;
+import com.sun.source.tree.MemberSelectTree;
+import com.sun.source.tree.Tree;
+import com.sun.tools.javac.code.Symbol;
+import java.util.Optional;
+import javax.lang.model.element.AnnotationMirror;
+
+abstract class AnnotationChecker extends BugChecker implements IdentifierTreeMatcher,
+    MemberSelectTreeMatcher, CompilationUnitTreeMatcher {
```
Comment (ericgribkoff) [inline src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java]: I think we should drop the `CompilationUnitTreeMatcher` interface here: There doesn't seem to be a need to skip checking code in an `io.grpc.*` package - this tool will not be run on gRPC library code, and this code becomes simpler if we can drop the `shouldBeChecked` logic altogether.

I did see that removing this logic causes trouble in the tests due to gRPC's annotations themselves being annotated as `@Internal`. This is fixed in https://github.com/grpc/grpc-java/pull/4051

File: src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java [hunk 10]
```diff
@@ -0,0 +1,105 @@
...
+
+  AnnotationChecker(String basePackage, String annotationType) {
+    this.annotationType = checkNotNull(annotationType, "annotationType");
+    this.basePackage = checkNotNull(basePackage, "packageName");
+  }
+
+  /**
+   * Returns true if api is annotated.
+   */
+  private Optional<AnnotationMirror> findAnnotatedApi(Symbol symbol) {
```
Comment (ericgribkoff) [inline src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java]: Can we drop use the use of `Optional` here? While errorprone requires JDK8, it can still be used to build JDK6/7 code (http://errorprone.info/docs/installation), so it may be best to avoid the use of JDK8-specific features (I didn't dig too deeply into how backwards compatibility works in this scenario, so `Optional` may not actually pose a problem in this scenario). This becomes not too much different using a null return value:

```
  /**
   * Returns non-null if api is annotated.
   */
  private AnnotationMirror findAnnotatedApi(Symbol symbol) {
    if (symbol == null) {
      return null;
    }
    for (AnnotationMirror annotation : symbol.getAnnotationMirrors()) {
      if (annotation.getAnnotationType().toString().equals(annotationType)) {
        return annotation;
      }
    }
    // recursive
    return findAnnotatedApi(symbol.owner);
  }
```

File: src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java [hunk 11]
```diff
@@ -0,0 +1,105 @@
...
+import com.sun.source.tree.MemberSelectTree;
+import com.sun.source.tree.Tree;
+import com.sun.tools.javac.code.Symbol;
+import java.util.Optional;
+import javax.lang.model.element.AnnotationMirror;
+
+abstract class AnnotationChecker extends BugChecker implements IdentifierTreeMatcher,
+    MemberSelectTreeMatcher, CompilationUnitTreeMatcher {
+
+  private boolean shouldBeChecked = false;
```
Comment (ericgribkoff) [inline src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java]: If we drop the `io.grpc.*` package test, this can be removed.

File: src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java [hunk 12]
```diff
@@ -0,0 +1,105 @@
...
+  private final String annotationType;
+  private final String basePackage;
```
Comment (ericgribkoff) [inline src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java]: If we drop the `io.grpc.*` package test, this can be removed.

File: src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java [hunk 13]
```diff
@@ -0,0 +1,105 @@
...
+    return match(tree, state);
+  }
+
+  @Override
+  public Description matchMemberSelect(MemberSelectTree tree, VisitorState state) {
+    return match(tree, state);
+  }
+
+  // TODO(jyane): verify order.
+  // Compilation unit tree would be matched first and then other trees would be matched. Really?
```
Comment (ericgribkoff) [inline src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java]: Dropping the `io.grpc.*` package test also means we don't have to worry about this question :)

File: src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java [hunk 14]
```diff
@@ -0,0 +1,105 @@
...
+
+  /**
+   * Returns the description if tree is annotated.
+   */
+  private Description match(Tree tree, VisitorState state) {
+    Symbol symbol = ASTHelpers.getSymbol(tree);
+    if (!shouldBeChecked || symbol == null) {
+      return NO_MATCH;
+    }
+    return findAnnotatedApi(symbol)
```
Comment (ericgribkoff) [inline src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java]: Without Java 8 this would be replaced with something like:

```    
    AnnotationMirror annotation = findAnnotatedApi(symbol);
    if (annotation == null) {
      return NO_MATCH;
    }
    return describe(tree, annotation);
```

File: src/main/java/io/grpc/annotations/checkers/ExperimentalApiChecker.java [hunk 15]
```diff
@@ -0,0 +1,67 @@
...
+    linkType = LinkType.CUSTOM,
+    link = "https://github.com/grpc/grpc-java"
+)
+public final class ExperimentalApiChecker extends AnnotationChecker {
+
+  public ExperimentalApiChecker() {
+    super("io.grpc", "io.grpc.ExperimentalApi");
+  }
+
+  private Optional<String> findLink(AnnotationMirror annotation) {
```
Comment (ericgribkoff) [inline src/main/java/io/grpc/annotations/checkers/ExperimentalApiChecker.java]: I think it'd be preferable to avoid the use of `Optional` here too. How about:

```
  private String findLink(AnnotationMirror annotation) {
    // Currently, @ExperimentalApi may have a link.
    for (Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : annotation
        .getElementValues().entrySet()) {
      return entry.getValue().toString();
    }
    return this.linkUrl();
  }
```

File: src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java [hunk 16]
```diff
@@ -0,0 +1,498 @@
...
+    // add the @Internal annotation
+    compiler.addSourceLines("io/grpc/Internal.java",
+        "package io.grpc;",
+        "import java.lang.annotation.Documented;",
+        "import java.lang.annotation.ElementType;",
+        "import java.lang.annotation.Retention;",
+        "import java.lang.annotation.RetentionPolicy;",
+        "import java.lang.annotation.Target;",
+        "",
+        "@Internal",
```
Comment (ericgribkoff) [inline src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java]: This can be deleted now that it's corrected upstream (https://github.com/grpc/grpc-java/pull/4051)

Comment (ericgribkoff) [reply src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java]: Actually, now that `@Experimental` is not itself annotated as `@Internal`, the `Internal.java` source here can be dropped entirely (sorry for the headache around our annotation updates)

File: src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java [hunk 17]
```diff
@@ -0,0 +1,498 @@
...
+    compiler.addSourceLines("io/grpc/ExperimentalApi.java",
+        "package io.grpc;",
+        "",
+        "import java.lang.annotation.Documented;",
+        "import java.lang.annotation.ElementType;",
+        "import java.lang.annotation.Retention;",
+        "import java.lang.annotation.RetentionPolicy;",
+        "import java.lang.annotation.Target;",
+        "",
+        "@Internal",
```
Comment (ericgribkoff) [inline src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java]: This can be deleted now that it's corrected upstream (grpc/grpc-java#4051)

File: src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java [hunk 18]
```diff
@@ -0,0 +1,498 @@
...
+            "  public static void main(String args[]) {",
+            "    System.out.println(args);",
+            "  }",
+            "}")
+        .doTest();
+  }
+
+  // Test for compilation unit matching
+  @Test
+  public void negativeDefaultPackageCouldEvaluate() {
```
Comment (ericgribkoff) [inline src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java]: I'm not sure what this one is testing - can it be dropped if we are no longer excluding `io.grpc.*` code?

File: src/test/java/io/grpc/annotations/checkers/InternalCheckerTest.java [hunk 19]
```diff
@@ -0,0 +1,473 @@
...
+    // add the @Internal annotation
+    compiler.addSourceLines("io/grpc/Internal.java",
+        "package io.grpc;",
+        "import java.lang.annotation.Documented;",
+        "import java.lang.annotation.ElementType;",
+        "import java.lang.annotation.Retention;",
+        "import java.lang.annotation.RetentionPolicy;",
+        "import java.lang.annotation.Target;",
+        "",
+        "@Internal",
```
Comment (ericgribkoff) [inline src/test/java/io/grpc/annotations/checkers/InternalCheckerTest.java]: This can also now be removed (https://github.com/grpc/grpc-java/pull/4051)

File: src/test/java/io/grpc/annotations/checkers/InternalCheckerTest.java [hunk 20]
```diff
@@ -0,0 +1,473 @@
...
+            "  public static void main(String args[]) {",
+            "    System.out.println(args);",
+            "  }",
+            "}")
+        .doTest();
+  }
+
+  // Test for compilation unit matching
+  @Test
+  public void negativeDefaultPackageCouldEvaluate() {
```
Comment (ericgribkoff) [inline src/test/java/io/grpc/annotations/checkers/InternalCheckerTest.java]: As before - can this be dropped if we aren't excluding `io.grpc.*` packages?

**Review by ericgribkoff — COMMENTED** [review]
Ok, I think I got through everything. Looks really good overall, and test coverage looks solid.

Main suggested change is just to drop the implementation of the `CompilationUnitTreeMatcher` interface. We don't need to exclude `io.grpc.*` packages from the checker, and dropping this will simplify the checker code and logic quite a bit. (https://github.com/grpc/grpc-java/pull/4051 and https://github.com/grpc/grpc-java/pull/4039 take care of some problems in grpc-java's use of annotations that were brought to light by this work)

File: examples/build.gradle (hunk 8 above)
Comment (jyane) [reply examples/build.gradle]: I thought I should add more concrete examples (using the `protoc` like the HelloWorld in grpc-java examples).

File: src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java (hunk 9 above)
Comment (jyane) [reply src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java]: Dropped. It makes simplify this tool, thanks!

File: src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java (hunk 10 above)
Comment (jyane) [reply src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java]: Dropped.
I think the private method is controllable so changing null value is no problem :)

File: src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java (hunk 13 above)
Comment (jyane) [reply src/main/java/io/grpc/annotations/checkers/AnnotationChecker.java]: Thanks!

File: src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java (hunk 16 above)
Comment (jyane) [reply src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java]: Synced.

File: src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java (hunk 18 above)
Comment (jyane) [reply src/test/java/io/grpc/annotations/checkers/ExperimentalApiCheckerTest.java]: Dropped.

**Comment by jyane** [comment]
I think I've addressed all comments. And CI is green.

**Comment by jyane** [comment]
@ericgribkoff I think adding the Bazel example is needed. I will create another PR :)

File: README.md [hunk 21]
```diff
@@ -0,0 +1,66 @@
...
+[![Build Status](https://travis-ci.org/grpc/grpc-java-api-checker.svg?branch=master)](https://travis-ci.org/grpc/grpc-java-api-checker)
+
+An Error Prone plugin that checks for usages of grpc-java APIs that are annotated with `@ExperimentalApi` or `@Internal`.
+
+**NOTE: grpc-java-api-checker works with grpc-java version 1.10.0 or greater.**
+
+The error examples:
+
+```
+src/main/java/com/example/App.java:10: error: [Internal] @Internal should not be used in application code
```
Comment (ericgribkoff) [inline README.md]: This will now output `[GrpcInternal]` as the checker name

File: README.md [hunk 22]
```diff
@@ -0,0 +1,66 @@
...
+    System.out.println(InternalStatus.MESSAGE_KEY);
+                       ^
+    (see https://github.com/grpc/grpc-java)
+
+src/main/java/com/example/App.java:11: error: [ExperimentalApi] @ExperimentalApi should not be used in application code
```
Comment (ericgribkoff) [inline README.md]: (and `[GrpcExperimentalApi]`)

**Review by ericgribkoff — APPROVED** [review]
Two minor documentation comments, but otherwise LGTM! Thanks for all your work on this!

**Comment by jyane** [comment]
Oops...
I will fix them, at night (Japan Standard Time).

Thank you very much for all your energy (@ericgribkoff and ejona86)!

**Comment by jyane** [comment]
I will change a commit message to `initial import` and do "squash and merge"

**Comment by jyane** [comment]
Thanks!
